Solution
tshtk/hh-school-2021-java-collections-stream pull request #1
Opened 2021-12-22 19:17 UTC by tshtk

Solution

2021-12-23 08:43 UTC, genroelgvozo requested changes

2021-12-23 08:43 UTC, genroelgvozo commented on src/tasks/Task8.java
> +  и если эта логика здесь не необходима то переписал бы метод через стрим, для этого сделал статичным метод getFullName
а если необходима, через стримы не работает? ну и да, логику менять не хотелось бы (сейчас если id повторяется, что у тебя случится?)

2021-12-23 08:43 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    else return (person.getSecondName() + " " + person.getFirstName());
работать будет. а если отчество добавить?) сколько там будет ифов?)

посмотри в сторону Collectors.joining - в стриме и отфильтровать можно, и понятно какие данные берем, и багов нет (у тебя их тоже нет, в изначальном еще был баг про пробел в начале)

2021-12-23 08:43 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    intersection.retainAll(persons2);
немного костыльная, хотя по скорости быстрая
а можно без изменения? например .stream().anyMatch, или Collections.disjoint
с доп памятью на сет ок, а если его не делать?

2021-12-23 08:43 UTC, genroelgvozo commented on src/tasks/Task8.java
> +  Этот метод будто лишний здесь, как и объявление переменной count в классе, а не в теле метода
в можно в теле?) а ты попробуй)
и еще, этот метод просто на стримы, показать как плохо. Сейчас он может выдать неверный результат, подумай почемУ, и напиши как верно

2021-12-30 13:39 UTC, tshtk commented on src/tasks/Task8.java
> +  и если эта логика здесь не необходима то переписал бы метод через стрим, для этого сделал статичным метод getFullName
если id повторяется, вылетело бы исключение.
Исправил:
return persons.stream().collect(Collectors.toMap(Person::getId, Task8::getFullName, (a1, a2) -> a1));

2021-12-30 13:40 UTC, tshtk commented on src/tasks/Task8.java
> +    else return (person.getSecondName() + " " + person.getFirstName());
Исправил:
return Stream.of(person.getFirstName(), person.getSecondName())
            .filter(Objects::nonNull).collect(Collectors.joining(" "));

2021-12-30 13:42 UTC, tshtk commented on src/tasks/Task8.java
> +  Этот метод будто лишний здесь, как и объявление переменной count в классе, а не в теле метода
Почему может выдать неверный результат, не придумал.
Придумал, как упростить:
return numbers.filter(num -> num % 2 == 0).count();

2021-12-30 13:43 UTC, tshtk commented on src/tasks/Task8.java
> +    intersection.retainAll(persons2);
С Collections.disjoint хорошо получается:
return !Collections.disjoint(persons1, persons2);

2021-12-30 13:46 UTC, merged